// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnjvnwvbssxldbrwwdpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuanZud3Zic3N4bGRicnd3ZHBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTg0ODIsImV4cCI6MjA2MjkzNDQ4Mn0.L4dST1RglmT_-Zo8x2VR8rJsk2fYdCEDOsiRg2EJaY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);